[package]
name = "ssh-manager"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
clap_complete = "4.5.60"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "6.0"
rustyline = "17.0.2"
